repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: detect-private-key
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black
        language: python
        language_version: python3.9
        types: [python]
        files: ^python_deploy/
      - id: flake8
        name: flake8
        entry: flake8
        language: python
        language_version: python3.9
        types: [python]
        files: ^python_deploy/
      - id: mypy
        name: mypy
        entry: mypy
        language: python
        language_version: python3.9
        types: [python]
        files: ^python_deploy/
